CREATE TABLE rfcs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT UNSIGNED NOT NULL,
    project_id BIGINT UNSIGNED NULL,
    related_governance_record_id BIGINT UNSIGNED NULL,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    status ENUM('draft','under_review','approved','rejected','converted_to_decision') NOT NULL DEFAULT 'draft',
    submitted_at TIMESTAMP NULL,
    reviewed_by BIGINT UNSIGNED NULL,
    reviewed_at TIMESTAMP NULL,
    review_note TEXT NULL,
    resulting_decision_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_rfc_code (workspace_id, code),
    KEY idx_rfc_status (workspace_id, status),
    CONSTRAINT fk_rfc_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
    CONSTRAINT fk_rfc_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_rfc_govrecord FOREIGN KEY (related_governance_record_id) REFERENCES governance_records(id),
    CONSTRAINT fk_rfc_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id),
    CONSTRAINT fk_rfc_decision FOREIGN KEY (resulting_decision_id) REFERENCES decision_registers(id),
    CONSTRAINT fk_rfc_created_by FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
