-- Phase 1 / M1 Foundation — revisions
-- Tracks Dev revisions submitted for CTO review
CREATE TABLE revisions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NOT NULL,
    workspace_id BIGINT UNSIGNED NOT NULL,
    milestone_id BIGINT UNSIGNED NULL,
    repository_id BIGINT UNSIGNED NULL,
    status ENUM('submitted','cto_approved','cto_rejected','committed') NOT NULL DEFAULT 'submitted',
    summary TEXT NOT NULL,
    test_result ENUM('passed','failed','skipped','pending') NOT NULL DEFAULT 'pending',
    branch VARCHAR(150) NULL,
    commit_hash VARCHAR(64) NULL,
    push_status ENUM('pending','success','failed') NOT NULL DEFAULT 'pending',
    known_issue TEXT NULL,
    next_action TEXT NULL,
    dev_user_id BIGINT UNSIGNED NULL,
    dev_ai_consumer_id BIGINT UNSIGNED NULL,
    submitted_by BIGINT UNSIGNED NOT NULL,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    committed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_rev_project (project_id),
    KEY idx_rev_workspace (workspace_id),
    KEY idx_rev_milestone (milestone_id),
    KEY idx_rev_status (status),
    CONSTRAINT fk_rev_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_rev_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
    CONSTRAINT fk_rev_milestone FOREIGN KEY (milestone_id) REFERENCES milestones(id),
    CONSTRAINT fk_rev_repository FOREIGN KEY (repository_id) REFERENCES repositories(id),
    CONSTRAINT fk_rev_dev_user FOREIGN KEY (dev_user_id) REFERENCES users(id),
    CONSTRAINT fk_rev_dev_ai FOREIGN KEY (dev_ai_consumer_id) REFERENCES ai_consumers(id),
    CONSTRAINT fk_rev_submitted_by FOREIGN KEY (submitted_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;